
# 1. CE: Sum of Digits
# sum the digits of a positive integer

x_(paste(12358134L)) $ xToChars() $ xMap(as.numeric) $ x_Reduce("+")

# 27

# 2. Read in protein sequence data, and then find the most frequent
# amino acid.

dgcr8 <- xFromLines_(
	"METDESPSPLPCGPAGEAVMESRA",
	"RPFQALPREQSPPPPLQTSSGAEV",
	"MDVGSGGDGQSELPAEDPFNFYGA",
	"SLLSKGSFSKGRLLIDPNCSGHSP",
	"RTARHAPAVRKFSPDLKLLKDVKI",
	"SVSFTESCRSKDRKVLYTGAERDV",
	"RAECGLLLSPVSGDVHACPFGGSV",
	"GDGVGIGGESADKKDEENELDQEK",
	"RVEYAVLDELEDFTDNLELDEEGA",
	"GGFTAKAIVQRDRVDEEALNFPYE",
	"DDFDNDVDALLEEGLCAPKKRRTE",
	"EKYGGDSDHPSDGETSVQPMMTKI",
	"KTVLKSRGRPPTEPLPDGWIMTFH",
	"NSGVPVYLHRESRVVTWSRPYFLG",
	"TGSIRKHDPPLSSIPCLHYKKMKD",
	"NEEREQSSDLTPSGDVSPVKPLSR",
	"SAELEFPLDEPDSMGADPGPPDEK",
	"DPLGAEAAPGALGQVKAKVEVCKD",
	"ESVDLEEFRSYLEKRFDFEQVTVK",
	"KFRTWAERRQFNREMKRKQAESER",
	"PILPANQKLITLSVQDAPTKKEFV",
	"INPNGKSEVCILHEYMQRVLKVRP",
	"VYNFFECENPSEPFGASVTIDGVT",
	"YGSGTASSKKLAKNKAARATLEIL",
	"IPDFVKQTSEEKPKDSEELEYFNH",
	"ISIEDSRVYELTSKAGLLSPYQIL",
	"HECLKRNHGMGDTSIKFEVVPGKN",
	"QKSEYVMACGKHTVRGWCKNKRVG",
	"KQLASQKILQLLHPHVKNWGSLLR",
	"MYGRESSKMVKQETSDKSVIELQQ",
	"YAKKNKPNLHILSKLQEEMKRLAE",
	"EREETRKKPKMSIVASAQPGGEPL",
	"CTVDV")

x_(dgcr8) $ xToChars() $ xTabulate() $ x_MaxBy(xSecondOf)

# list('E', 77)
# Glutamic Acid is the most common residue in dgcr8
