
# 1. CE: Sum of Digits
# sum the digits of a positive integer

x_(toString(12358134L)) $ xToChars() $ xMap(as.numeric) $ x_Reduce("+")

# 27

# 2. Read in protein sequence data, and then find the most frequent
# amino acid.

dgcr8 <- xFromLines_(
	"METDESPSPLPCGPAGEAVMESRARPFQALPREQSPPPPLQTSSGAEVMDVGSGGDGQSELPAEDPFNFYGASLLSKGSF",
	"SKGRLLIDPNCSGHSPRTARHAPAVRKFSPDLKLLKDVKISVSFTESCRSKDRKVLYTGAERDVRAECGLLLSPVSGDVHA",
	"CPFGGSVGDGVGIGGESADKKDEENELDQEKRVEYAVLDELEDFTDNLELDEEGAGGFTAKAIVQRDRVDEEALNFPYEDDF",
	"DNDVDALLEEGLCAPKKRRTEEKYGGDSDHPSDGETSVQPMMTKIKTVLKSRGRPPTEPLPDGWIMTFHNSGVPVYLHRESRVV",
	"TWSRPYFLGTGSIRKHDPPLSSIPCLHYKKMKDNEEREQSSDLTPSGDVSPVKPLSRSAELEFPLDEPDSMGADPGPPDEKDPLG",
	"AEAAPGALGQVKAKVEVCKDESVDLEEFRSYLEKRFDFEQVTVKKFRTWAERRQFNREMKRKQAESERPILPANQKLITLSVQDAP",
	"TKKEFVINPNGKSEVCILHEYMQRVLKVRPVYNFFECENPSEPFGASVTIDGVTYGSGTASSKKLAKNKAARATLEILIPDFVKQTSE",
	"EKPKDSEELEYFNHISIEDSRVYELTSKAGLLSPYQILHECLKRNHGMGDTSIKFEVVPGKNQKSEYVMACGKHTVRGWCKNKRVGKQLA",
	"SQKILQLLHPHVKNWGSLLRMYGRESSKMVKQETSDKSVIELQQYAKKNKPNLHILSKLQEEMKRLAEEREETRKKPKMSIVASAQPGGEPL",
	"CTVDV")

x_(dgcr8) $ xToChars() $ xTabulate() $ x_MaxBy(xSecondOf)

# list('E', 77)
# Glutamic Acid is the most common residue in dgcr8
