# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cChunk <- function(num, coll) {
    .Call('kea_cChunk', PACKAGE = 'kea', num, coll)
}

cDrop <- function(num, coll) {
    .Call('kea_cDrop', PACKAGE = 'kea', num, coll)
}

cGroupBy <- function(fn, coll) {
    .Call('kea_cGroupBy', PACKAGE = 'kea', fn, coll)
}

cImplode <- function(str, strs) {
    .Call('kea_cImplode', PACKAGE = 'kea', str, strs)
}

cIsIn <- function(val, coll) {
    .Call('kea_cIsIn', PACKAGE = 'kea', val, coll)
}

cIsPrefixOf <- function(coll1, coll2) {
    .Call('kea_cIsPrefixOf', PACKAGE = 'kea', coll1, coll2)
}

cIsSubsetOf <- function(coll1, coll2) {
    .Call('kea_cIsSubsetOf', PACKAGE = 'kea', coll1, coll2)
}

cNotIn <- function(val, coll) {
    .Call('kea_cNotIn', PACKAGE = 'kea', val, coll)
}

cNotSubsetOf <- function(coll1, coll2) {
    .Call('kea_cNotSubsetOf', PACKAGE = 'kea', coll1, coll2)
}

cPowerSetOf <- function(coll) {
    .Call('kea_cPowerSetOf', PACKAGE = 'kea', coll)
}

cRiffle <- function(val, coll) {
    .Call('kea_cRiffle', PACKAGE = 'kea', val, coll)
}

cSwap <- function(val1, val2, coll) {
    .Call('kea_cSwap', PACKAGE = 'kea', val1, val2, coll)
}

cTabulate <- function(coll) {
    .Call('kea_cTabulate', PACKAGE = 'kea', coll)
}

cTake <- function(num, coll) {
    .Call('kea_cTake', PACKAGE = 'kea', num, coll)
}

cUnzipIndices <- function(coll) {
    .Call('kea_cUnzipIndices', PACKAGE = 'kea', coll)
}

cUnzipKeys <- function(coll) {
    .Call('kea_cUnzipKeys', PACKAGE = 'kea', coll)
}

cZip <- function(colls) {
    .Call('kea_cZip', PACKAGE = 'kea', colls)
}

cZipKeys <- function(colls) {
    .Call('kea_cZipKeys', PACKAGE = 'kea', colls)
}

