# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cChunk <- function(num, coll) {
    .Call('kea_cChunk', PACKAGE = 'kea', num, coll)
}

cDrop <- function(num, coll) {
    .Call('kea_cDrop', PACKAGE = 'kea', num, coll)
}

cFromChars <- function(strs) {
    .Call('kea_cFromChars', PACKAGE = 'kea', strs)
}

cPowerSetOf <- function(coll) {
    .Call('kea_cPowerSetOf', PACKAGE = 'kea', coll)
}

cTake <- function(num, coll) {
    .Call('kea_cTake', PACKAGE = 'kea', num, coll)
}

