
#' xAsFunction
#'
#' Convert a collection to a function that takes an index.
#'
#' @param
#'    coll a collection
#'
#' @param
#'    ... see above.
#'
#' @return
#'    A function that takes one or more indices.
#'
#' @section Corner Cases:
#'    Returns the empty list if \code{coll is length-zero}.
#'
#' @family function_modifying_functions
#'
#' @template
#'    Variadic
#'
#' @example
#'    inst/examples/example-xAsFunction.R
#'
#'
#' @example
#'    inst/examples/example-xAsFunction.R
#'
#' @rdname xAsFunction
#' @export

xAsFunction <- function (coll) {
	# Collection any -> (... -> [any])
	# enclose a collection in a function, and
	# allow access by supplying indices.

	invoking_call <- sys.call()

	assert(
		!missing(coll), invoking_call,
		exclaim$parametre_missing(coll))

	insist$must_be_collection(coll, invoking_call)

	function (...) {
		"a function generated by xAsFunction."
		""
		nums <- c(...)
		insist$must_be_collection(nums, invoking_call)
		nums <- to_value_unit(as_typed_vector(nums, 'numeric'))

		insist$must_be_whole(nums, invoking_call)
		insist$max_must_be_less_than_length_of(nums, coll, invoking_call)
		insist$minimum_must_be_greater_than(nums, 0, invoking_call)

		as.list(coll[nums])
	}
}

#'
#' @rdname xAsFunction
#' @export

xAsFunction... <- function (...) {
	xAsFunction(list(...))
}
